---
version: '2'
services:
    app42:
        build:
              context: ./
              dockerfile: Dockerfile
        volumes:
              - volume1:/home/App42PaaS-Java-MySQL-Sample/target
    deploy:
        image: dockertn3/tomcat-alpine-msfonts:latest
        ports:
              - '8080:8080'
        volumes:
              - volume1:/var/lib/tomcat9/webapps

    mysql:
        image:  mysql/mysql-server
        ports:
              - '3306:3306'
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_USER: app42
            MYSQL_PASSWORD: qwerty123

volumes:
  volume1:
