---
version: '2'
services:
    app42:
        build:
              context: ./
              dockerfile: Dockerfile
        volumes:
              - volume1:/home/Paas42/target
    deploy:
              context: ./
              dockerfile: Dockerfile3
              - '8080:8080'
        volumes:
              - volume1:/usr/local/tomcat/webapps

    mysql:
        image:  mysql/mysql-server
        ports:
              - '3306:3306'
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_USER: app42
            MYSQL_PASSWORD: qwerty123

volumes:
  volume1:
